import { ThemeProvider } from "next-themes";
import CmsNavbar from "../Components/CmsNavbar";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <CmsNavbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
